codecov:
  require_ci_to_pass: yes

comment:
  layout: " diff, flags, files"
  behavior: default
  require_changes: false
  require_base: true
  require_head: true
  hide_project_coverage: false

coverage:
  precision: 2
  round: down
  range: "70...100"

parsers:
  javascript:
    enable_partials: true

ignore:
  - "examples/*"
  - "test-utils/*"
  - "**/*.stories.tsx"