codecov:
  require_ci_to_pass: yes

comment:
  layout: "condensed_header, condensed_files, condensed_footer"
  require_changes: false
  require_head: true
  require_base: false
  hide_project_coverage: true


coverage:
  precision: 2
  round: down
  range: "70...100"

parsers:
  javascript:
    enable_partials: true

ignore:
  - "examples/*"
  - "test-utils/*"
  - "**/*.stories.tsx"