name: NPM Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: NPM Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: npm ci

      - name: Set Git User Info (for version commit)
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Bump Patch Version
        run: |
          npm version patch --no-git-tag-version
          git add package.json package-lock.json
          git commit -m "ci: bump version for auto-publish"

      - name: Build Package
        run: npm run build

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Push Version Commit and Tag
        run: |
          git tag v$(node -p "require('./package.json').version")
          git push origin main --tags